name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-24.04
    steps:
      - run: python --version
      - uses: actions/checkout@v4     #mi gitclono la repo
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: ls -la #vedo che file ci sono
      - run: python --version
      - run: uname -a
      - run: pip install pytest
      - run: pip instal -r requirement.txt
      - run: pytest